=head1 Authors

This book is the work of many contributors.  They are listed below.

=item Jonathan Worthington

Jonathan a prolific contributor to the Rakudo compiler.  He is primarily responsible for the implementation of Rakudo's object system.

=item Patrick R. Michaud  

Patrick is the chief architect of Rakudo, the Parrot-based Perl 6 compiler.

=item Carl Mäsak

Carl builds applications using Rakudo.  He has submitted over 500 Rakudo-related bug tickets.  Sometimes he actually fixes things, too.

=item Moritz Lenz

=item Jonathan Scott Duff
