=head1 NAME

Outline - what to explain in which chapter

=head1 DESCRIPTION

we need some kind of plan where we want to put what. Here's a very rough plan,
feel free to adapt and improve.

=head1 STRUCTURE

=head2  Chapter 1 - the basics

Lexical conventions, literals, variables, scalars, arrays, hashes, basic
operators, method and function calls, control flow.

(Add more basics here if you need them in later chapters).

(How can we make that chapter non-boring? keeping it short?)

TODO: more about arrays, hashes, built-in functions and methods, operators,
list quoting

=head2 Chapter 2 - Operators, meta operators

TODO: everything

=head2 Chapter 3 - Subs and signatures,
   
=head2 Chapter 4 - multis

Typed based multi dispatch, narrowness, constraints, multiple arguments

=head2 Chapter 5 - Objects and classed

classes, attributes, methods, construction

TODO:

inheritance, BUILD submethods

=head2 Chapter 6 - Regexes 

Literals, quantifiers, captures, anchors, look-arounds, backtracking control,
match objects

TODO:

??

=head2 Chapter 7 - Grammars

Subrules, recursion, inheritance, reduction methods

TODO: detailed explanation of the JSON reduction methods

=head2 Chapter 8 - Roles (?)

=head1 Conjectural: chapter ideas

Other suggestions:

    database interface
    web programming

