BUILD_STRATEGY := xelatex
XELATEX                := xelatex

BINARY_TARGET_DIR := ../dist

default_graphic_extension	?= pdf
latex_build_program		?= $(XELATEX)
build_target_extension		?= pdf
hyperref_driver_pattern		?= hdvipdf.*
hyperref_driver_error		?= Using pdflatex: specify pdftex in the hyperref options (or leave it blank).
