=head0 Preface

Perl 6 has had a long gestation period. During that time several
implementations have been created. These implementations have, in turn,
informed the design of Perl 6 in ways that wouldn't have been possible
without developers trying to implement the specification and programmers
trying to use those implementations to solve real programming problems.
Because of this interplay between design and implementation, today we
have more cohesive and consistent language specification and a compiler
that implements a good bit of it. 

In the pages that follow, you will be introduced to the Perl 6 language
through its Rakudo implementation. Good luck and as the Perl 6 community
often says: have fun!

This book is a work-in-progress, and it is expected that even releases
will contain some amount of C<TODO> comments prior to the printing of the
book.  We've left them in because they might serve as useful cues for the
reader as well as for us authors about what remains to be done. Even so,
we pray the reader's indulgence and understanding.

=head1 Audience

This book is primarily for people who want to learn Perl 6 and have some
experience programming in another programming language. However, no
prior knowledge of Perl is necessary. After working through this book, a
programmer should have a solid grasp of the basics of Perl 6. That means
that they should be able to solve their own problems with Perl 6. This
book is not a comprehensive reference. It is a series of tutorials.

=head1 Perl 6 implementations

Perl 6 is a specification. Any implementation that passes the official
test suite can call itself "Perl 6". There are currently several
implementations at various levels of maturity. All of the code in this
book is tested using the Rakudo implementation of Perl 6.

=head1 Organization of the Book

Each chapter is a mini-tutorial covering some aspect of Perl 6.
Later chapters build on concepts introduced in earlier chapters.
Each chapter contains a sample program in its entirety followed by
prose that explains the code in detail.

=head1 Installing Rakudo

Complete instructions for downloading and installing Rakudo can be found
at U<http://www.rakudo.org/how-to-get-rakudo>. Source code releases are
available from U<http://github.com/rakudo/rakudo/downloads>. A binary
release for windows is available from
U<http://sourceforge.net/projects/parrotwin32/files/>.

=head1 Executing programs

To run a Perl 6 program with Rakudo, include the install directory in
your system PATH variable and issue a command like:

    $ perl6 hello.pl

If the Rakudo compiler is invoked without an explicit script to run, it
enters a small interactive mode that allows Perl 6 statements to be
executed from the command line. Each line entered is treated as a
separate compilation unit, however (which means that subroutines are
preserved after they are defined, but variables are not).

=head1 Getting involved

If you are inspired by the contents of this book and want to contribute
to the Perl 6 community, there are more resources available to you:

=over

=item IRC

There is a channel #perl6 on irc.freenode.net dedicated to all things Perl 6.

=item Mailing Lists

For issues regarding the Perl 6 language specification send email to
C<perl6-language@perl.org>, for issues regarding the compiler send email to
C<perl6-compiler@perl.org>

=back

=head1 Acknowledgements

=for editors

Surely we'll want to thank some people!  :-)

=end for

